connect 'D:/DB/SERVICE.FDB' user 'SYSDBA' password 'masterkey';
commit;

-- 3 --
create view DET_ALL_S as
	select ORDERS_SOA.ID_DETAIL, sum(ORDERS_SOA.AMOUNT) as AMOUNT
	from ORDERS_SOA
	group by ORDERS_SOA.ID_DETAIL;

create view DET_ALL_Y as
	select DET_ALL_S.ID_DETAIL, DET_ALL_S.AMOUNT, 
		DETAILS_CATALOG.VIN, DETAILS_CATALOG.ID_DETAIL_NAME
	from DET_ALL_S, DETAILS_CATALOG
	where DET_ALL_S.ID_DETAIL = DETAILS_CATALOG.ID_DETAIL
		and DETAILS_CATALOG.ORIGINAL =  'y';

create view DET_ALL_N_1 as
	select DET_ALL_S.ID_DETAIL, DET_ALL_S.AMOUNT, 
		DETAILS_CATALOG.VIN, DETAILS_CATALOG.ID_DETAIL_NAME
	from DET_ALL_S, DETAILS_CATALOG
	where DET_ALL_S.ID_DETAIL = DETAILS_CATALOG.ID_DETAIL
		and DETAILS_CATALOG.ORIGINAL =  'n';

create view DET_ALL_N as
	select DET_ALL_N_1.VIN, DET_ALL_N_1.ID_DETAIL_NAME, sum(DET_ALL_N_1.AMOUNT) as AMOUNT
	from DET_ALL_N_1
	group by DET_ALL_N_1.VIN, DET_ALL_N_1.ID_DETAIL_NAME;

create view TOP_10_DET as 
	select first 10 DET_ALL_Y.ID_DETAIL, (DET_ALL_N.AMOUNT - DET_ALL_Y.AMOUNT) as AMT
	from DET_ALL_Y, DET_ALL_N
	where DET_ALL_Y.VIN = DET_ALL_N.VIN and DET_ALL_Y.ID_DETAIL_NAME = DET_ALL_N.ID_DETAIL_NAME
	order by AMT desc;

select * from DET_ALL_S where ID_DETAIL <= 50;
select * from DET_ALL_Y;
select first 5 * from DET_ALL_N;
select * from TOP_10_DET; 
